#' outputs data frame in tidy format from gee list
#'
#' @description this function will take the list generated by the xxtolist() functions and outputs into datafram with coordinates and data in tidy format
#'
#' @param list the list that is returned from one of the xxtolist() functions
#'
#' @return
#' @export
#'
#' @examples
#' ROI = ROI()
#' list = wttolist(ROI, "20010928", 5, 30000)
#' df = geetodf(list)
#'
geetodf = function(list){
  for (i in 1:length(list$features[])) {
    unli = unlist(list$features[[i]]$properties)
    te = list$features[[i]]$geometry$coordinates
    if(i == 1) {
      data = data.frame(lon = te[1], lat = te[2])
      for (j in 1:length(list$columns)) {
        data[[names(unli[j])]] = unli[[j]]
      }
    }
    else{
      data[i,] = c(te[1],te[2], rep(NA, length(list$columns)))
      for (j in 1:length(list$columns)) {
        data[i,j+2] = unli[[j]]
      }
    }
  }
  return(data)
}
